- assets/index.css
- index.html
메인 화면을 구현하였습니다. 메인 화면의 컨텐츠 부분은 추후 협의할 예정이라고 생각하여 모두 완성하진 않았습니다.
header와 footer가 공통적 부분이기에 이 부분을 구현하는 데에 중점을 두었습니다.
+ 추가로, 변경 사항으론 클래스 이름 변경이 있습니다. 이유는 부트스랩과의 충돌 때문입니다. container -> Container
> #page1 메인(로그인 전)

- assets/css/register_for_admin.css
- assets/css/register_for_user.css
- login.html
- register_choice.html
- register_for_admin.html
- register_for_user.html
> #page4 회원가입

- assets/css/register_for_admin.css
- assets/css/register_for_user.css
- login.html
- register_choice.html
- register_for_admin.html
- register_for_user.html
1) 관리자용 회원가입
2) 사용자용 회원가입을 구현했습니다
> #page4 회원가입 구현(정규 표현식 X)

- assets/css/index.css
- index_admin.html
- index_user.html
1) [사용자]메인(로그인 후)
2) [관리자[메인(로그인 후)
둘 다 구현하였습니다.
> #page 메인(로그인 후) 구현

- assets/js/login.js
feat 브랜치 - 주석 작성 및 pull request test
> #feat - 주석

- assets/css/locker_for_admin.css
- assets/css/locker_for_user.css
- locker_for_admin.html
- locker_for_user.html
> #feat - 사물함 (사용자, 관리자) 화면 틀

- assets/css/locker_for_admin.css
- assets/css/locker_for_user.css
- locker_for_admin.html
- locker_for_user.html
> #feat - 사물함 (사용자, 관리자) 화면 틀 - 재호님 작업

- readme.md
> Update readme.md - 재호님 작업

- assets/css/mypage_user.css
- mypage_admin.html
1. 회원 정보(이름, 이메일, 학번) 칸 추가
2. 프로필 사진 추가
3. 관리자 마이페이지 구현
-> 예약 확인 칸만 빼면 사용자와 똑같음
> #page mypage(사용자,관리자) 수정 및 구현

- assets/css/mypage_user.css
- mypage_admin.html
1. 회원 정보(이름, 이메일, 학번) 칸 추가
2. 프로필 사진 추가
3. 관리자 마이페이지 구현
-> 예약 확인 칸만 빼면 사용자와 똑같음
>  #page mypage(사용자,관리자) 수정 및 구현 - 지원님

- myapp/routes/index.js
> #bugfix 오타 수정

- myapp/public/javascripts/make_locker.js
- myapp/public/stylesheets/locker_for_admin.css
- myapp/public/stylesheets/locker_for_user.css
- myapp/views/locker_for_admin.html
- myapp/views/locker_for_user.html
- myapp/views/register_for_admin.html
1) 가로, 세로를 입력받고 사물함을 생성합니다
2) 클릭 시 회색으로 변하고, 다시 클릭 시 원래 색으로 돌아옵니다.
> #feat [관리자]사물함생성 구현(일부)

- myapp/public/javascripts/select_place.js
- myapp/public/javascripts/select_place2.js
- myapp/views/locker_for_admin.html
- myapp/views/locker_for_user.html
카카오맵 API 코드를 넣었습니다.
select option value에 따라 다른 지도를 보여주게 할 생각입니다.
> #feat 사물함의 건물 위치 지도

- myapp/public/javascripts/select_place.js
- myapp/views/locker_for_admin.html
- myapp/views/locker_for_user.html
1) 반복되는 코드 -> 자바스크립트 코드로 뺐습니다.
2) 기존의 하드 코딩된 위경도를 fetch 함수를 이용하여 서버와의 통신으로 받아오도록 하였습니다.
> #cleancode

- myapp/views/mypage_admin.html
- myapp/views/mypage_user.html
> #page - mypage 비밀번호 확인 기능 수정

- myapp/public/javascripts/mypage_user.js
- myapp/public/stylesheets/locker_for_admin.css
- myapp/public/stylesheets/locker_for_user.css
- myapp/public/stylesheets/mypage_admin.css
- myapp/public/stylesheets/register_choice.css
- myapp/views/index_admin.html
- myapp/views/index_user.html
- myapp/views/locker_for_user.html
- myapp/views/mypage_admin.html
- myapp/views/mypage_user.html
- myapp/views/register_choice.html
#page mypage_user 보완
1. 예약 취소 버튼 클릭 시 모달창 띄움 -> 모달창에 예약 내역 보여주면서 취소 재확인 -> '네' 클릭 시 예약 내역 없애고 그 자리에 '예약하러 가기' 버튼 생성(;새로고침하면 다시 예약 내역 예시가 뜸)
2. mypage 헤더도 다른 헤더처럼 js적용 + 로그아웃 버튼 hover시 색상 변경
3. resgister_choice 버튼 hover시 색상 수정
* Apply .gitignore
> #page mypage_user 보완

- myapp/public/javascripts/mypage_user.js
- myapp/public/stylesheets/locker_for_admin.css
- myapp/public/stylesheets/locker_for_user.css
- myapp/public/stylesheets/mypage_admin.css
- myapp/public/stylesheets/register_choice.css
- myapp/views/index_admin.html
- myapp/views/index_user.html
- myapp/views/locker_for_user.html
- myapp/views/mypage_admin.html
- myapp/views/mypage_user.html
- myapp/views/register_choice.html
#page mypage_user 보완
1. 예약 취소 버튼 클릭 시 모달창 띄움 -> 모달창에 예약 내역 보여주면서 취소 재확인 -> '네' 클릭 시 예약 내역 없애고 그 자리에 '예약하러 가기' 버튼 생성(;새로고침하면 다시 예약 내역 예시가 뜸)
2. mypage 헤더도 다른 헤더처럼 js적용 + 로그아웃 버튼 hover시 색상 변경
3. resgister_choice 버튼 hover시 색상 수정
> #page mypage_user 보완 - 지원님 작업

- myapp/public/javascripts/select_locker.js
- myapp/public/javascripts/select_place.js
- myapp/views/locker_for_admin.html
- myapp/views/locker_for_user.html
사용자 :
'사물함 건물'을 선택 후 '사물함 이름'을 선택할 수 있습니다
'사물함 이름'은 관리자가 정한 이름으로
'사물함 건물'을 기준으로 DB에서 조회하여 '사물함 이름' select에 나타납니다.
관리자 :
'사물함 건물'을 선택 후 '사물함 이름'을 정하여 생성합니다.
> #page - 사물함 건물, 사물함 생성 및 수정

- myapp/public/javascripts/select_locker.js
- myapp/public/javascripts/select_place.js
- myapp/views/locker_for_admin.html
- myapp/views/locker_for_user.html
사용자 :
'사물함 건물'을 선택 후 '사물함 이름'을 선택할 수 있습니다
'사물함 이름'은 관리자가 정한 이름으로
'사물함 건물'을 기준으로 DB에서 조회하여 '사물함 이름' select에 나타납니다.
관리자 :
'사물함 건물'을 선택 후 '사물함 이름'을 정하여 생성합니다.
> #page - 사물함 건물, 사물함 생성 및 수정 - 재호님 작업

- myapp/public/javascripts/login.js
- myapp/views/layout/login_for_admin.ejs
- myapp/views/layout/login_for_user.ejs
1. 이메일 정규식 ~@sju.ac.kr로 변경
2. 틀렸을 때 "올바른 이메일을 입력해주세요."문구 뜨고, 맞으면 문구 없앰
3. 틀린 이메일이면 제출 버튼 눌러도 제출 안되고 alert띄움
> #bugfix 로그인 오류

- myapp/public/javascripts/login.js
- myapp/views/layout/login_for_admin.ejs
- myapp/views/layout/login_for_user.ejs
1. 이메일 정규식 ~@sju.ac.kr로 변경
2. 틀렸을 때 "올바른 이메일을 입력해주세요."문구 뜨고, 맞으면 문구 없앰
3. 틀린 이메일이면 제출 버튼 눌러도 제출 안되고 alert띄움
> #bugfix 로그인 오류 - 지원님 작업

- myapp/public/javascripts/form_check.js
- myapp/public/javascripts/nav_items.js
- myapp/public/javascripts/register.js
- myapp/views/layout/header.ejs
- myapp/views/layout/header_mypage.ejs
- myapp/views/layout/login_for_admin.ejs
- myapp/views/layout/login_for_user.ejs
- myapp/views/layout/register_form.ejs
1) login email 버그 수정
2) checkbox 라디오버튼 -> 체크버튼
3) navbar 우측정렬
> #bugfix - 재호님 작업

- myapp/app.js
- myapp/package-lock.json
- myapp/package.json
1. body-parser, mysql를 install 하였습니다.
2. app.js에 간단히 mysql 연동 부분의 코드를 넣어봤습니다.
> #feat 필요한 모듈 추가 및 코드 업데이트

- myapp/public/javascripts/dropdown.js
- myapp/public/stylesheets/index.css
- myapp/public/stylesheets/mypage_admin.css
- myapp/public/stylesheets/mypage_user.css
- myapp/public/stylesheets/register_choice.css
- myapp/public/stylesheets/register_for_admin.css
- myapp/public/stylesheets/register_for_user.css
- myapp/views/index.ejs
- myapp/views/index_admin.ejs
- myapp/views/index_user.ejs
- myapp/views/layout/footer.ejs
- myapp/views/layout/footer_for_admin.ejs
- myapp/views/layout/footer_for_user.ejs
- myapp/views/layout/header.ejs
- myapp/views/layout/header_mypage.ejs
- myapp/views/layout/register_form.ejs
- myapp/views/register_choice.ejs
- myapp/views/register_for_admin.ejs
- myapp/views/register_for_user.ejs
#cleancode 색 통일, footer 수정
1. 버튼, a:hover 색 통일(다른 색으로 변경O)
2. footer의 pages 내용 변경
-> footer(login X), footer_for_user, footer_for_admin으로 나눠서 내용 수정
3. footer의 문의하기 수정
-> input을 textarea로 수정, 엔터로 줄바꾸기 O, 넘치면 자동으로 줄바꾸기 O
> #cleancode 색 통일, footer 수정 - 지원님 작업

- myapp/app.js
- myapp/routes/controllers.js
- myapp/routes/index.js
> #cleancode controller 분리

- myapp/views/index.ejs
- myapp/views/index_admin.ejs
- myapp/views/index_user.ejs
- myapp/views/locker_for_admin.ejs
- myapp/views/locker_for_user.ejs
- myapp/views/login.ejs
- myapp/views/mypage_admin.ejs
- myapp/views/mypage_user.ejs
- myapp/views/register_choice.ejs
- myapp/views/register_for_admin.ejs
- myapp/views/register_for_user.ejs
> #cleancode 경로 수정

- myapp/public/javascripts/login.js
- myapp/routes/index.js
- myapp/views/layout/login_for_admin.ejs
- myapp/views/layout/login_for_user.ejs
- myapp/views/register_for_admin.ejs
- myapp/views/register_for_user.ejs
기존에 a.href를 통해서 링크로 접속하던 방식에서 form method를 통하여 들어가는 방식으로 수정하였습니다. 그에 따라 라우팅도 추가되었습니다.
> #bugfix 로그인, 회원가입 action 수정

- myapp/public/javascripts/login.js
- myapp/public/javascripts/register.js
- myapp/views/layout/login_for_admin.ejs
- myapp/views/layout/login_for_user.ejs
- myapp/views/layout/register_for_admin.ejs
- myapp/views/layout/register_for_user.ejs
- myapp/views/layout/register_form.ejs
- myapp/views/register_choice.ejs
- myapp/views/register_for_admin.ejs
- myapp/views/register_for_user.ejs
1) 유효한 값이 아니어도 가입이 되어 페이지가 넘어가는 버그를 수정하였습니다.
2) 유효한 값이 아니어도 로그인이 되어 페이지가 넘어가는 버그를 수정하였습니다.
> #bugfix 여러 오류 수정

- myapp/app.js
- myapp/package-lock.json
- myapp/package.json
> #feat 모듈 설치

- myapp/app.js
- myapp/routes/controllers.js
> #feat 세션 코드 입력

- myapp/public/javascripts/email_check.js
- myapp/public/javascripts/login.js
- myapp/views/layout/login_for_admin.ejs
- myapp/views/layout/login_for_user.ejs
1. 학번으로 로그인하게 바꾸면서 기존 login.js를 email_check.js로 파일 이름 변경
2. 새로운 login.js
-> 학번이나 비밀번호를 입력하지 않았을 경우(공백일 경우) 경고 문구 표시, 공백인 상태로 로그인 버튼 누를 시 alert
> #cleancode 로그인 학번으로 수정

- myapp/routes/controllers.js
- myapp/routes/index.js
- myapp/views/layout/header_mypage.ejs
> #feat 로그인 로그아웃 구현

- myapp/routes/controllers.js
- myapp/routes/index.js
- myapp/views/layout/login_for_admin.ejs
- myapp/views/layout/login_for_user.ejs
1) 로그인 로그아웃을 process라는 객체 안에서 관리하도록 하였습니다.
2) 마이페이지 등도 세션에 따라 다른 화면이 나오도록 설정하였습니다.
> #feat 로그인, 로그아웃 구현

- myapp/routes/controllers.js
- myapp/routes/index.js
컨트롤러에 사용되는 객체 변수명을 카멜 표기법으로 변경하였습니다. 혹여 잘 실행되지 않을 수도 있으므로 기존 코드는 지우지 않고 남겨두었습니다.
> #cleancode 컨트롤러 변수명 변경

- myapp/app.js
- myapp/db/config.js
- myapp/package-lock.json
- myapp/package.json
- myapp/routes/controllers.js
- myapp/routes/index.js
- myapp/views/layout/register_form.ejs
- myapp/views/register_for_admin.ejs
- myapp/views/register_for_user.ejs
1) 사용자 회원가입 구현하였습니다.(관리자는 아직입니다.)
2) 회원가입 과정을 따로 처리하는 registerProcess를 만들었습니다.
> #feat 사용자 회원가입 기능 추가(진행중)

- myapp/routes/controllers.js
> #feat 사용자 회원가입 구현

- myapp/public/javascripts/form_check.js
- myapp/routes/controllers.js
- myapp/views/layout/register_form.ejs
- myapp/views/register_choice.ejs
관리자의 회원가입 기능과 로그인 기능을 구현하였습니다.
> #feat 관리자 회원가입, 로그인 구현

- myapp/app.js
- myapp/public/javascripts/select_place.js
- myapp/routes/controllers.js
- myapp/routes/index.js
- myapp/views/error.ejs
1) 500 에러에 따른 예외처리를 구현했습니다.
2) 사용자, 관리자 리스트를 출력하는 기능을 만들었습니다. (추후에 사용할 예정입니다.)
> #feat 예외처리, 리스트 구현

- myapp/routes/controllers.js
render -> rediect 로 수정 및 버그 수정
> #bugfix - 회원탈퇴 버그 수정

- myapp/routes/controllers.js
> #bugfix - 회원탈퇴 버그 수정 (재호님 작업)

- myapp/routes/controllers.js
> #bugfix 세션 삭제 추가

- myapp/routes/controllers.js
- myapp/routes/index.js
- myapp/views/login.ejs
> #feat rest 구조의 컨트롤러 추가

- myapp/routes/controllers.js
> #cleancode 라우터 정리

- myapp/public/stylesheets/mypage_user.css
- myapp/routes/controllers.js
- myapp/views/layout/change_profile.ejs
- myapp/views/mypage_for_admin.ejs
- myapp/views/mypage_for_user.ejs
1. 임시로 표시해 놨던 회원 정보 대신 사용자, 관리자 db에서 정보(비밀번호 제외) 가져와서 정보 칸에 표시
;null값은 공백
> #cleancode mypage 회원정보 출력

- myapp/public/stylesheets/mypage_user.css
- myapp/routes/controllers.js
- myapp/views/layout/change_profile.ejs
- myapp/views/mypage_for_admin.ejs
- myapp/views/mypage_for_user.ejs
1. 임시로 표시해 놨던 회원 정보 대신 사용자, 관리자 db에서 정보(비밀번호 제외) 가져와서 정보 칸에 표시
;null값은 공백
> #cleancode mypage 회원정보 출력 - 지원님 작업

- myapp/public/javascripts/nav_items.js
- myapp/public/stylesheets/login.css
- myapp/routes/controllers.js
- myapp/views/index_admin.ejs
- myapp/views/index_user.ejs
- myapp/views/layout/footer_for_admin.ejs
- myapp/views/layout/footer_for_user.ejs
- myapp/views/layout/header_mypage.ejs
- myapp/views/layout/login_for_admin.ejs
- myapp/views/layout/login_for_user.ejs
- myapp/views/locker_for_admin.ejs
- myapp/views/locker_for_user.ejs
- myapp/views/mypage_for_admin.ejs
- myapp/views/mypage_for_user.ejs
1. 헤더에 마이페이지 버튼을 누르면 나오는 리스트의 '회원님'을 사용자의 이름+님 으로 변경
2. header_mypage로 분리하지 않고 각 파일에 header 코드 포함시킴
-> 사용자/관리자에 맞는 헤더로 내용 변경, 링크 연결
3. 로그인 폼 하단에 비밀번호 찾기 추가(동작x)
> #cleancode 헤더 정리

- myapp/public/javascripts/nav_items.js
- myapp/public/stylesheets/login.css
- myapp/routes/controllers.js
- myapp/views/index_admin.ejs
- myapp/views/index_user.ejs
- myapp/views/layout/footer_for_admin.ejs
- myapp/views/layout/footer_for_user.ejs
- myapp/views/layout/header_mypage.ejs
- myapp/views/layout/login_for_admin.ejs
- myapp/views/layout/login_for_user.ejs
- myapp/views/locker_for_admin.ejs
- myapp/views/locker_for_user.ejs
- myapp/views/mypage_for_admin.ejs
- myapp/views/mypage_for_user.ejs
1. 헤더에 마이페이지 버튼을 누르면 나오는 리스트의 '회원님'을 사용자의 이름+님 으로 변경
2. header_mypage로 분리하지 않고 각 파일에 header 코드 포함시킴
-> 사용자/관리자에 맞는 헤더로 내용 변경, 링크 연결
3. 로그인 폼 하단에 비밀번호 찾기 추가(동작x)
> #cleancode 헤더 정리 - 지원님 작업

- myapp/public/javascripts/nav_items.js
- myapp/routes/controllers.js
- myapp/routes/index.js
- myapp/views/index.ejs
- myapp/views/index_admin.ejs
- myapp/views/index_user.ejs
- myapp/views/layout/footer_for_admin.ejs
- myapp/views/layout/footer_for_user.ejs
- myapp/views/layout/header.ejs
- myapp/views/layout/header_mypage.ejs
- myapp/views/locker.ejs
- myapp/views/mypage.ejs
1) index 통합
2) mypage 통합
3) locker 통합
4) 외에 자잘한 통일 작업들 했습니다.
버그 발생시 알려주시면 감사하겠습니다.
> 전체적인 틀을 잡았습니다.

- myapp/views/index.ejs
- myapp/views/layout/footer.ejs
- myapp/views/mypage.ejs
1. footer 통합
2. 로그인 후에도 헤더에 home, locker 뜨게 수정
3. 마이페이지 학번 뜨게 수정
> #cleancode footer 통합

- myapp/public/stylesheets/mypage_user.css
- myapp/views/layout/change_profile.ejs
- myapp/views/mypage_for_admin.ejs
- myapp/views/mypage_for_user.ejs
비밀번호 변경 : submit -> button 으로 임시변경,
form 태그 분류해서 수정 완료
> #bugfix - 회원탈퇴 form tag 수정

- myapp/routes/controllers.js
- myapp/routes/index.js
- myapp/views/layout/change_profile.ejs
- myapp/views/mypage.ejs
사용자, 관리자가 새로운 비밀번호를 입력한 뒤 비밀번호 변경 버튼을 누르면 비밀번호가 변경되며, 세션 삭제 후 로그인 창으로 이동하게 구현하였습니다..
> #feat 비밀번호 변경 기능 추가

- myapp/routes/controllers.js
- myapp/views/locker.ejs
- myapp/views/mypage.ejs
1. 관리자 소속이 인덱스 값으로 표시돼서 이름으로 표시되게 했습니다.
-> admin 테이블의 team에 체크박스 인덱스 값이 들어가 있습니다. 일단 다른 방법을 못찾겠어서 team 테이블을 추가해서 거기에 소속값(학생회, 교내 동아리, ...)을 insert해 admin 테이블의 team값과 동일한 id를 갖는 것의 이름을 가져오도록 했습니다.
2. locker 헤더 링크연결
> #bugfix 마이페이지(관리자) 소속 수정

- myapp/routes/controllers.js
- myapp/views/locker.ejs
- myapp/views/mypage.ejs
1. 관리자 소속이 인덱스 값으로 표시돼서 이름으로 표시되게 했습니다.
-> admin 테이블의 team에 체크박스 인덱스 값이 들어가 있습니다. 일단 다른 방법을 못찾겠어서 team 테이블을 추가해서 거기에 소속값(학생회, 교내 동아리, ...)을 insert해 admin 테이블의 team값과 동일한 id를 갖는 것의 이름을 가져오도록 했습니다.
2. locker 헤더 링크연결
> #bugfix 마이페이지(관리자) 소속 수정 - 지원님 작업
